steps:
  # Install dependencies
  - name: 'node:22'
    dir: 'todo-app'
    entrypoint: npm
    args: ['ci']

  # Create .env file
  - name: 'node:22'
    dir: 'todo-app'
    entrypoint: 'npm'
    args: ['run', 'create-env', '.env']
    secretEnv: ['_APIKEY']
    env:
      - 'NEXT_PUBLIC_API_KEY=$$_APIKEY'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--no-promote']
    dir: 'todo-app'

# Access secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/${_AR_PROJECT_ID}/secrets/jessikey/versions/latest
      env: 'jessikey'

timeout: '1600s' 

options:
  logging: CLOUD_LOGGING_ONLY
